### ISSUE TITLE
В AmusementPark невозможно добавить локацию конкретного типа

### ISSUE THREAD

**Issue by igel2000** [GulnazaS/amusement-park#8]
Нужно всё-таки переделывать так, чтобы add принимал экземпляр класса-наследника от Location()

**Comment by igel2000** [comment]
Т.е. код должен быть примерно таким:
```
  park = AmusementPark(...)
  attr = Attraction(...)
  park.add_location (attr)
  shop = Shop(...)
  park.add_location (shop)

```

**Comment by AntoxaZ18** [comment]
@igel2000 Я планировал изначально в таком виде как будут готовы классы
```
park = AmusementPark(...)
park.add_location (Attraction, args, kwargs)
```

где Attraction - имя класса которое создать надо. То есть парк внутри себя сам объекты создает. Как лучше оставить?

**Comment by igel2000** [comment]
В модуле attraction. Но его ты не можешь импортировать в модуле amusement_park.

Если хочется проверить, как AmusementPark будет работать с конкретными классами, то стоит создать amusement_park_test.py, в котором писать тот код, который у тебя под `if __name__ == '__main__':`. 
Вот там уже можно импортировать всё, что хочешь
